jobs:
  sales_pipeline_job:
    name: sales_pipeline_job
    tasks:
      - task_key: bronze
        notebook_task:
          notebook_path: /Shared/pipeline/01_bronze_ingestion
        job_cluster_key: sales_cluster

      - task_key: silver
        depends_on:
          - task_key: bronze
        notebook_task:
          notebook_path: /Shared/pipeline/02_silver_transformation
        job_cluster_key: sales_cluster

      - task_key: gold
        depends_on:
          - task_key: silver
        notebook_task:
          notebook_path: /Shared/pipeline/03_gold_aggregation
        job_cluster_key: sales_cluster

    job_clusters:
      - job_cluster_key: sales_cluster
        new_cluster:
          spark_version: 13.3.x-scala2.12
          node_type_id: Standard_DS3_v2
          num_workers: 2
